src/Entity/Borrowing.php
<?php

namespace App\Entity;

use App\Repository\BorrowingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BorrowingRepository::class)]
#[ORM\Table('borrowings')]

class Borrowing
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $borrow_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $expected_return_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $actual_return_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $comment = null;

    #[ORM\ManyToOne(inversedBy: 'relate_to')]
    private ?Material $material = null;

    #[ORM\ManyToOne(inversedBy: 'concern')]
    private ?TrainingProgram $trainingProgram = null;

    #[ORM\ManyToOne(inversedBy: 'make')]
    private ?Student $student = null;

    #[ORM\ManyToOne(inversedBy: 'manage')]
    private ?Employee $employee = null;

    #[ORM\ManyToOne(inversedBy: 'borrow')]
    private ?Employee $employee_borrow = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBorrowDate(): ?\DateTimeInterface
    {
        return $this->borrow_date;
    }

    public function setBorrowDate(\DateTimeInterface $borrow_date): static
    {
        $this->borrow_date = $borrow_date;

        return $this;
    }

    public function getExpectedReturnDate(): ?\DateTimeInterface
    {
        return $this->expected_return_date;
    }

    public function setExpectedReturnDate(\DateTimeInterface $expected_return_date): static
    {
        $this->expected_return_date = $expected_return_date;

        return $this;
    }

    public function getActualReturnDate(): ?\DateTimeInterface
    {
        return $this->actual_return_date;
    }

    public function setActualReturnDate(\DateTimeInterface $actual_return_date): static
    {
        $this->actual_return_date = $actual_return_date;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }
    private $borrowerType;

    public function getBorrowerType(): ?string
    {
        return $this->borrowerType;
    }

    public function setBorrowerType(string $borrowerType): self
    {
        $this->borrowerType = $borrowerType;

        return $this;
    }

    public function getMaterial(): ?Material
    {
        return $this->material;
    }

    public function setMaterial(?Material $material): static
    {
        $this->material = $material;

        return $this;
    }

    public function getTrainingProgram(): ?TrainingProgram
    {
        return $this->trainingProgram;
    }

    public function setTrainingProgram(?TrainingProgram $trainingProgram): static
    {
        $this->trainingProgram = $trainingProgram;

        return $this;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): static
    {
        $this->student = $student;

        return $this;
    }

    public function getEmployee(): ?Employee
    {
        return $this->employee;
    }

    public function setEmployee(?Employee $employee): static
    {
        $this->employee = $employee;

        return $this;
    }

    public function getEmployeeBorrow(): ?Employee
    {
        return $this->employee_borrow;
    }

    public function setEmployeeBorrow(?Employee $employee_borrow): static
    {
        $this->employee_borrow = $employee_borrow;

        return $this;
    }
}

src/Entity/Material.php
<?php

namespace App\Entity;

use App\Repository\MaterialRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MaterialRepository::class)]
#[ORM\Table('materials')]

class Material
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $serial_number = null;

    #[ORM\Column(length: 50)]
    private ?string $tag_number = null;

    #[ORM\Column(length: 255)]
    private ?string $comment = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $location = null;

    #[ORM\Column]
    private ?bool $is_available = null;

    #[ORM\ManyToOne(inversedBy: 'belong_to')]
    private ?MaterialKind $materialKind = null;

    #[ORM\OneToMany(targetEntity: Borrowing::class, mappedBy: 'material')]
    private Collection $relate_to;

    public function __construct()
    {
        $this->relate_to = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSerialNumber(): ?string
    {
        return $this->serial_number;
    }

    public function setSerialNumber(string $serial_number): static
    {
        $this->serial_number = $serial_number;

        return $this;
    }

    public function getTagNumber(): ?string
    {
        return $this->tag_number;
    }

    public function setTagNumber(string $tag_number): static
    {
        $this->tag_number = $tag_number;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function isIsAvailable(): ?bool
    {
        return $this->is_available;
    }

    public function setIsAvailable(bool $is_available): static
    {
        $this->is_available = $is_available;

        return $this;
    }

    public function getMaterialKind(): ?MaterialKind
    {
        return $this->materialKind;
    }

    public function setMaterialKind(?MaterialKind $materialKind): static
    {
        $this->materialKind = $materialKind;

        return $this;
    }

    /**
     * @return Collection<int, Borrowing>
     */
    public function getRelateTo(): Collection
    {
        return $this->relate_to;
    }

    public function addRelateTo(Borrowing $relateTo): static
    {
        if (!$this->relate_to->contains($relateTo)) {
            $this->relate_to->add($relateTo);
            $relateTo->setMaterial($this);
        }

        return $this;
    }

    public function removeRelateTo(Borrowing $relateTo): static
    {
        if ($this->relate_to->removeElement($relateTo)) {
            // set the owning side to null (unless already changed)
            if ($relateTo->getMaterial() === $this) {
                $relateTo->setMaterial(null);
            }
        }

        return $this;
    }
}

src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
#[ORM\Table('students')]

class Student
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birthdate = null;

    #[ORM\OneToMany(targetEntity: Borrowing::class, mappedBy: 'student')]
    private Collection $make;

    #[ORM\Column]
    private ?bool $is_active = null;

    public function __construct()
    {
        $this->make = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): static
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    /**
     * @return Collection<int, Borrowing>
     */
    public function getMake(): Collection
    {
        return $this->make;
    }

    public function addMake(Borrowing $make): static
    {
        if (!$this->make->contains($make)) {
            $this->make->add($make);
            $make->setStudent($this);
        }

        return $this;
    }

    public function removeMake(Borrowing $make): static
    {
        if ($this->make->removeElement($make)) {
            // set the owning side to null (unless already changed)
            if ($make->getStudent() === $this) {
                $make->setStudent(null);
            }
        }

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }
}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Student;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname', null , ['label' => "Prénom"])
            ->add('lastname', null , ['label' => "Nom"])
            ->add('birthdate')
            ->add('is_active', CheckboxType::class, [
                'required' => false,
                'label' => 'Actif',
                'attr' => [
                    'class' => 'form-check-input'
                ],
                'row_attr' => [
                    'class' => 'form-check form-switch'
                ]
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Form\StudentType;
use App\Repository\BorrowingRepository;
use App\Repository\StudentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/student')]
class StudentController extends AbstractController
{
    #[Route('/', name: 'app_student_index', methods: ['GET'])]
    public function index(StudentRepository $studentRepository): Response
    {
        $user = $this->getUser();
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        return $this->render('student/index.html.twig', [
            'students' => $studentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_student_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $student = new Student();
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($student);
            $entityManager->flush();

            return $this->redirectToRoute('app_student_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('student/new.html.twig', [
            'student' => $student,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_student_show', methods: ['GET'])]
    public function show(Student $student,BorrowingRepository  $borrowingRepository): Response
    {
        // dd($student->id);
        $user_borrow = $borrowingRepository->findBy(array('student' => $student->getId()));
        // dd($user_borrow);

        return $this->render('student/show.html.twig', [
            'student' => $student,
            'user_borrows' => $user_borrow
        ]);
    }

    #[Route('/{id}/edit', name: 'app_student_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Student $student, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_student_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('student/edit.html.twig', [
            'student' => $student,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_student_delete', methods: ['POST'])]
    public function delete(Request $request, Student $student, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$student->getId(), $request->request->get('_token'))) {
            $entityManager->remove($student);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_student_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/student/_delete_form.html.twig
<form method="post" action="{{ path('app_student_delete', {'id': student.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ student.id) }}">
    <button class="btn">Delete</button>
</form>

templates/student/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/student/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Student{% endblock %}
 {% block headTitle %}Modifier un étudiant{% endblock %}

{% block body %}

    {{ include('student/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_student_index') }}" class="btn btn_primary">back to list</a>

    {{ include('student/_delete_form.html.twig') }}
{% endblock %}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student index{% endblock %}
 {% block headTitle %}Liste des étudiants{% endblock %}

{% block body %}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Birthdate</th>
                <th>Is_active</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td>{{ student.id }}</td>
                <td>{{ student.firstname }}</td>
                <td>{{ student.lastname }}</td>
                <td>{{ student.birthdate ? student.birthdate|date('Y-m-d') : '' }}</td>
                <td>{{ student.isActive ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_student_show', {'id': student.id}) }}"><iconify-icon icon="carbon:view-filled" width="25"></iconify-icon></a>
                    <a href="{{ path('app_student_edit', {'id': student.id}) }}"><iconify-icon icon="material-symbols-light:edit" width="25"></iconify-icon></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_student_new') }}">Créer un nouvel étudiant</a>
{% endblock %}

templates/student/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Student{% endblock %}
 {% block headTitle %}Ajouter un étudiant{% endblock %}

{% block body %}
	<section class="new_employee">

    {{ include('student/_form.html.twig') }}

    <a href="{{ path('app_student_index') }}" class="btn primary_btn">back to list</a>
    <input type="submit" value="Create" class="btn primary_btn"/>
{% endblock %}

templates/student/show.html.twig
{% extends 'base.html.twig' %}
 {% block headTitle %}Détail d'un étudiant{% endblock %}

{% block title %}Student{% endblock %}

{% block body %}

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ student.id }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ student.firstname }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ student.lastname }}</td>
            </tr>
            <tr>
                <th>Birthdate</th>
                <td>{{ student.birthdate ? student.birthdate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Is_active</th>
                <td>{{ student.isActive ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_student_index') }}">back to list</a>

    <a href="{{ path('app_student_edit', {'id': student.id}) }}">edit</a>
    {{ include('student/_delete_form.html.twig') }}
    <h4>Mes emprunts</h4>
	<a href="{{ path('app_employee_index') }}">back to list</a>
    {# <div class="row"></div> #}
	{% for user_borrow in user_borrows %}
		<div class="card border-primary mb-3" style="max-width: 18rem;">
			<div class="card-header">Date d'emprunt : {{user_borrow.borrowDate|date('Y-m-d')}}</div>
			<div class="card-body text-primary">
				<h5 class="card-title">Element : {{user_borrow.material.name}} </h5>
                <h6 class="card-subtitle mb-2 text-muted">N° de série : {{user_borrow.material.tagNumber}}  </h6>
				{# <p class="card-text">{{user_borrow.material.comment}} </p>
			</div>
            <div class="card-footer bg-transparent border-primary">Date de retour :{{user_borrow.actual_return_date|date('Y-m-d H:i')}} </div> #}
		</div>
	{% else %}
		<p>Vous n'avez emporté aucun matériel</p>
	{% endfor %}
    {{ include('student/_delete_form.html.twig') }}
{% endblock %}
{% endblock %}