src/Entity/Material.php
<?php

namespace App\Entity;

use App\Repository\MaterialRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MaterialRepository::class)]
#[ORM\Table('materials')]

class Material
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $serial_number = null;

    #[ORM\Column(length: 50)]
    private ?string $tag_number = null;

    #[ORM\Column(length: 255)]
    private ?string $comment = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $location = null;

    #[ORM\Column]
    private ?bool $is_available = null;

    #[ORM\ManyToOne(inversedBy: 'belong_to')]
    private ?MaterialKind $materialKind = null;

    #[ORM\OneToMany(targetEntity: Borrowing::class, mappedBy: 'material')]
    private Collection $relate_to;

    public function __construct()
    {
        $this->relate_to = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSerialNumber(): ?string
    {
        return $this->serial_number;
    }

    public function setSerialNumber(string $serial_number): static
    {
        $this->serial_number = $serial_number;

        return $this;
    }

    public function getTagNumber(): ?string
    {
        return $this->tag_number;
    }

    public function setTagNumber(string $tag_number): static
    {
        $this->tag_number = $tag_number;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function isIsAvailable(): ?bool
    {
        return $this->is_available;
    }

    public function setIsAvailable(bool $is_available): static
    {
        $this->is_available = $is_available;

        return $this;
    }

    public function getMaterialKind(): ?MaterialKind
    {
        return $this->materialKind;
    }

    public function setMaterialKind(?MaterialKind $materialKind): static
    {
        $this->materialKind = $materialKind;

        return $this;
    }

    /**
     * @return Collection<int, Borrowing>
     */
    public function getRelateTo(): Collection
    {
        return $this->relate_to;
    }

    public function addRelateTo(Borrowing $relateTo): static
    {
        if (!$this->relate_to->contains($relateTo)) {
            $this->relate_to->add($relateTo);
            $relateTo->setMaterial($this);
        }

        return $this;
    }

    public function removeRelateTo(Borrowing $relateTo): static
    {
        if ($this->relate_to->removeElement($relateTo)) {
            // set the owning side to null (unless already changed)
            if ($relateTo->getMaterial() === $this) {
                $relateTo->setMaterial(null);
            }
        }

        return $this;
    }
}

src/Form/MaterialType.php
<?php

namespace App\Form;

use App\Entity\Material;
use App\Entity\MaterialKind;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class MaterialType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name',TextType::class,[
                'label'=>"Nom",
                'attr' => ['class' => 'textInput']

            ])
            ->add('serial_number',TextType::class,[
                'label'=>"N° de série",
                'attr' => ['class' => 'textInput']

            ])
            ->add('tag_number',TextType::class,[
                'label'=>"N° d'étiquette",
                'attr' => ['class' => 'textInput']
            ])
            ->add('comment',TextareaType::class,[
                'label'=>"Commentaire",
                'attr' => ['class' => 'textInput']
            ])
            // ->add('location')
            ->add('is_available',CheckboxType::class,[
                'label'=>"Est-il disponible ?",
                'required'=>false,
            ])
            ->add('materialKind', EntityType::class, [
                'class' => MaterialKind::class,
                'choice_label' => 'id',
                'label'=>"Type du matériel"
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Material::class,
            'submit_button_label' => 'Créer'
        ]);
    }
}

src/Controller/MaterialController.php
<?php

namespace App\Controller;

use App\Entity\Material;
use App\Form\MaterialType;
use App\Form\SearchType;
use App\Repository\MaterialRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;


#[Route('/material')]
class MaterialController extends AbstractController
{
    #[Route('/', name: 'app_material_index', methods: ['GET'])]
    public function index(Request $request, MaterialRepository $materialRepository): Response
{
    $user = $this->getUser();
    $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
    $searchQuery = $request->query->get('q');
    
    // Si une recherche est effectuée, filtrer les matériaux par ID
    if ($searchQuery) {
        // Utilisation d'une requête personnalisée avec LIKE SQL pour correspondre aux parties du numéro de série
        $materials = $materialRepository->createQueryBuilder('m')
            ->where('m.serial_number LIKE :searchQuery')
            ->setParameter('searchQuery', '%'.$searchQuery.'%')
            ->getQuery()
            ->getResult();
    } else {
        // Sinon, récupérer tous les matériaux
        $materials = $materialRepository->findAll();
    }
    
    return $this->render('material/index.html.twig', [
        'materials' => $materials,
    ]);
}

    

    #[Route('/new', name: 'app_material_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $material = new Material();
        $form = $this->createForm(MaterialType::class, $material);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($material);
            $entityManager->flush();

            return $this->redirectToRoute('app_material_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('material/new.html.twig', [
            'material' => $material,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_material_show', methods: ['GET'])]
    public function show(Material $material): Response
    {
        return $this->render('material/show.html.twig', [
            'material' => $material,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_material_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Material $material, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MaterialType::class, $material);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_material_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('material/edit.html.twig', [
            'material' => $material,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_material_delete', methods: ['POST'])]
    public function delete(Request $request, Material $material, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$material->getId(), $request->request->get('_token'))) {
            $entityManager->remove($material);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_material_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/material/_delete_form.html.twig
<form method="post" action="{{ path('app_material_delete', {'id': material.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ material.id) }}">
    <button class="btn primary_btn">Delete</button>
</form>

templates/material/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/material/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Material{% endblock %}
 {% block headTitle %}Détail d'un matériel{% endblock %}

{% block body %}
	<section class="new_employee">

        <div class="editMaterial">
            {{ include('material/_form.html.twig', {'button_label': 'Update'}) }}
        </div>
        <a href="{{ path('app_material_index') }}">back to list</a>

        {{ include('material/_delete_form.html.twig') }}
    </section>

{% endblock %}

templates/material/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Material index{% endblock %}
 {% block headTitle %}Historique du matériel{% endblock %}

{% block body %}

    <div class="searchdiv">
        <form class="globalSearchBar" action="{{ path('app_material_index') }}" method="GET">
            <input type="text" name="q" placeholder="Rechercher par numero de serie...">
            <button type="submit">Rechercher</button>
        </form>
    </div>


    <table class="materialsIndexTable">
        <thead>
            <tr>
                {# <th>Id</th> #}
                <th class="topLeft">Element</th>
                <th>N° d'étiquette</th>
                <th>N° de série</th>
                <th>Disponibilité</th>
                <th>Emprunteur</th>
                <th class="comment">Comment</th>
                <th class="topRight">actions</th>
            </tr>
        </thead>
        <tbody>
        {% set row_number = 0 %}
        {% for material in materials %}
            {% set row_number = row_number + 1 %}
            <tr class="{{ row_number is divisible by(2) ? 'even' : 'odd' }}">
                {# <td>{{ material.id }}</td> #}
                <td>{{ material.serialNumber }}</td>
                <td>{{ material.name }}</td>
                <td>{{ material.tagNumber }}</td>
                <td class="{% if material.isAvailable %}text-success{% else %}text-danger{% endif %}">
                    {{ material.isAvailable ? 'Disponible' : 'Non disponible' }}
                </td>
                <td>{{ material.location }}</td>
                <td>{{ material.comment }}</td>
                <td class="actions">
                    <a class="gg-eye" href="{{ path('app_material_show', {'id': material.id}) }}"><iconify-icon icon="carbon:view-filled" width="25"></iconify-icon></a>
                    <a class="gg-pen" href="{{ path('app_material_edit', {'id': material.id}) }}"><iconify-icon icon="material-symbols-light:edit" width="25"></iconify-icon></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">pas de matériel</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <a href="{{ path('app_material_new') }}" class="btn primary_btn">Créer un nouveau matériel</a>
{% endblock %}

templates/material/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Material{% endblock %}
 {% block headTitle %}Ajouter un matériel{% endblock %}

{% block body %}
	<section class="new_employee">

    <div class="createMaterial">
        {{ include('material/_form.html.twig') }}
    </div>
    <a href="{{ path('app_material_index') }}" class="btn btn_primary">back to list</a>
    </section>
{% endblock %}

templates/material/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Material{% endblock %}
 {% block headTitle %}Détail d'un matériel{% endblock %}

{% block body %}
<div class="showMaterial">
    <table class="table">
        <tbody>
            <tr class="toptr">
                <th class="topLeft">Id</th>
                <th>Name</th>
                <th>Serial_number</th>
                <th>Tag_number</th>
                <th>Comment</th>
                <th>Location</th>
                <th class="topRight">Is_available</th>
            </tr>
            <tr class="datatr">
                <td>{{ material.id }}</td>
                <td>{{ material.name }}</td>
                <td>{{ material.serialNumber }}</td>
                <td>{{ material.tagNumber }}</td>
                <td class="comment-cell"><span class="comment-content">{{ material.comment }}</span></td>
                <td>{{ material.location }}</td>
                <td>{{ material.isAvailable ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_material_index') }}">back to list</a>

    <a href="{{ path('app_material_edit', {'id': material.id}) }}">edit</a>

    {{ include('material/_delete_form.html.twig') }}
</div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const commentCell = document.querySelector('.comment-cell');
            const commentContent = document.querySelector('.comment-content');
            let isExpanded = false;

            commentCell.addEventListener('click', function() {
                if (isExpanded) {
                    commentContent.style.whiteSpace = 'nowrap';
                    commentContent.style.overflow = 'hidden';
                    commentContent.style.textOverflow = 'ellipsis';
                    isExpanded = false;
                } else {
                    commentContent.style.whiteSpace = 'normal';
                    commentContent.style.overflow = 'auto';
                    commentContent.style.textOverflow = 'unset';
                    isExpanded = true;
                }
            });
        });
    </script>
{% endblock %}