src/Entity/Borrowing.php
<?php

namespace App\Entity;

use App\Repository\BorrowingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BorrowingRepository::class)]
#[ORM\Table('borrowings')]

class Borrowing
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $borrow_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $expected_return_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $actual_return_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $comment = null;

    #[ORM\ManyToOne(inversedBy: 'relate_to')]
    private ?Material $material = null;

    #[ORM\ManyToOne(inversedBy: 'concern')]
    private ?TrainingProgram $trainingProgram = null;

    #[ORM\ManyToOne(inversedBy: 'make')]
    private ?Student $student = null;

    #[ORM\ManyToOne(inversedBy: 'manage')]
    private ?Employee $employee = null;

    #[ORM\ManyToOne(inversedBy: 'borrow')]
    private ?Employee $employee_borrow = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBorrowDate(): ?\DateTimeInterface
    {
        return $this->borrow_date;
    }

    public function setBorrowDate(\DateTimeInterface $borrow_date): static
    {
        $this->borrow_date = $borrow_date;

        return $this;
    }

    public function getExpectedReturnDate(): ?\DateTimeInterface
    {
        return $this->expected_return_date;
    }

    public function setExpectedReturnDate(\DateTimeInterface $expected_return_date): static
    {
        $this->expected_return_date = $expected_return_date;

        return $this;
    }

    public function getActualReturnDate(): ?\DateTimeInterface
    {
        return $this->actual_return_date;
    }

    public function setActualReturnDate(\DateTimeInterface $actual_return_date): static
    {
        $this->actual_return_date = $actual_return_date;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }
    private $borrowerType;

    public function getBorrowerType(): ?string
    {
        return $this->borrowerType;
    }

    public function setBorrowerType(string $borrowerType): self
    {
        $this->borrowerType = $borrowerType;

        return $this;
    }

    public function getMaterial(): ?Material
    {
        return $this->material;
    }

    public function setMaterial(?Material $material): static
    {
        $this->material = $material;

        return $this;
    }

    public function getTrainingProgram(): ?TrainingProgram
    {
        return $this->trainingProgram;
    }

    public function setTrainingProgram(?TrainingProgram $trainingProgram): static
    {
        $this->trainingProgram = $trainingProgram;

        return $this;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): static
    {
        $this->student = $student;

        return $this;
    }

    public function getEmployee(): ?Employee
    {
        return $this->employee;
    }

    public function setEmployee(?Employee $employee): static
    {
        $this->employee = $employee;

        return $this;
    }

    public function getEmployeeBorrow(): ?Employee
    {
        return $this->employee_borrow;
    }

    public function setEmployeeBorrow(?Employee $employee_borrow): static
    {
        $this->employee_borrow = $employee_borrow;

        return $this;
    }
}

src/Form/BorrowingType.php
<?php

namespace App\Form;

use App\Entity\Borrowing;
use App\Entity\Employee;
use App\Entity\Material;
use App\Entity\Student;
use App\Entity\TrainingProgram;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class BorrowingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('borrow_date',DateType::class,[
               'label'=>"Date d'emprunt" 
            ])
            ->add('expected_return_date',DateType::class,[
               'label'=>"Date de retour estimée" 
            ])
            ->add('actual_return_date',DateType::class,[
                'label'=>"Date de retour" ,
                'required' => false, 
                
            ])
            ->add('comment', TextareaType::class, [
                'label' => "Commentaire",
                'required' => false, 
            ])
            

            ->add('material', EntityType::class, [
                'class' => Material::class,
'choice_label' => 'name',
            ])
            ->add('trainingProgram', EntityType::class, [
                'class' => TrainingProgram::class,
'choice_label' => 'name',
            ])
            
            ->add('student', EntityType::class, [
                'class' => Student::class,
'choice_label' => 'firstname' ,
'required' => false, 
            ])
            ->add('employee', EntityType::class, [
                'class' => Employee::class,
'choice_label' => 'firstname',
'required' => false, 
            ])
//             ->add('employee_borrow', EntityType::class, [
//                 'class' => Employee::class,
// 'choice_label' => 'id',
//             ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Borrowing::class,
        ]);
    }
}

src/Controller/BorrowingController.php
<?php

namespace App\Controller;

use App\Entity\Borrowing;
use App\Form\BorrowingType;
use App\Repository\BorrowingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/borrowing')]
class BorrowingController extends AbstractController
{
    #[Route('/', name: 'app_borrowing_index', methods: ['GET'])]
    public function index(BorrowingRepository $borrowingRepository): Response
    {
        $user = $this->getUser();
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        return $this->render('borrowing/index.html.twig', [
            'borrowings' => $borrowingRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_borrowing_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $borrowing = new Borrowing();
        $form = $this->createForm(BorrowingType::class, $borrowing);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($borrowing);
            $entityManager->flush();

            return $this->redirectToRoute('app_borrowing_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('borrowing/new.html.twig', [
            'borrowing' => $borrowing,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_borrowing_show', methods: ['GET'])]
    public function show(Borrowing $borrowing): Response
    {
        return $this->render('borrowing/show.html.twig', [
            'borrowing' => $borrowing,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_borrowing_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Borrowing $borrowing, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(BorrowingType::class, $borrowing);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_borrowing_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('borrowing/edit.html.twig', [
            'borrowing' => $borrowing,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_borrowing_delete', methods: ['POST'])]
    public function delete(Request $request, Borrowing $borrowing, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$borrowing->getId(), $request->request->get('_token'))) {
            $entityManager->remove($borrowing);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_borrowing_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/borrowing/_delete_form.html.twig
<form method="post" action="{{ path('app_borrowing_delete', {'id': borrowing.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cet élément?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ borrowing.id) }}">

        <button class="btn">Supprimer</button>


</form>

templates/borrowing/_form.html.twig
{{ form_start(form) }}
    <div class="createMaterial">
        {{ form_widget(form) }}
    </div>
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/borrowing/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Borrowing{% endblock %}
 {% block headTitle %}Modifier un emprunt{% endblock %}

{% block body %}
{# <div class="title">
    <h1>Modifier un emprunt</h1>
</div> #}
    <div class="createMaterial">
        {{ include('borrowing/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    </div>

    <a href="{{ path('app_borrowing_index') }}">Retour a l'historique</a>

    {{ include('borrowing/_delete_form.html.twig') }}
{% endblock %}

templates/borrowing/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Borrowing index{% endblock %}
 {% block headTitle %}Historique des emprunts{% endblock %}

{% block body %}
    {# <div class="title">
        <h1>Historique des emprunts</h1>
    </div> #}

    <table class="materialsIndexTable">
        <thead>
            <tr>
                <th>Id</th>
                <th>Matériel emprunté</th>
                <th>Etudiant</th>
                <th>Date d'emprunt</th>
                <th>Date de retour attendue</th>
                <th>Date de retour</th>
                <th>Commentaires</th>
                <th>actions</th>
            </tr>
        </thead>
        
      
        <tbody>
        {% for borrowing in borrowings %}
            <tr>
                <td>{{ borrowing.id }}</td>
                <td>{{ borrowing.material.name }}</td>
                <td>
                    {% if borrowing.student is not null %}
                        {{ borrowing.student.firstname }}
                    {% else %}
                        Il n'y a personne
                    {% endif %}
                </td>
                <td>{{ borrowing.borrowDate ? borrowing.borrowDate|date('Y-m-d') : '' }}</td>
                <td>{{ borrowing.expectedReturnDate ? borrowing.expectedReturnDate|date('Y-m-d') : '' }}</td>

                <td>
                    {% if borrowing.actualReturnDate is not null %}
                        {{ borrowing.actualReturnDate|date('Y-m-d') }}
                    {% else %}
                        Aucune date de retour définie
                    {% endif %}
                </td>
                
                
                <td>
                    {% if borrowing.comment is not null %}
                        {{ borrowing.comment }}
                    {% else %}
                        RAS
                    {% endif %}
                </td>
                <td class="actions">
                    <a class="gg-eye" href="{{ path('app_borrowing_show', {'id': borrowing.id}) }}" ><iconify-icon icon="carbon:view-filled" width="25"></iconify-icon></a>
                    <a class="gg-pen" href="{{ path('app_borrowing_edit', {'id': borrowing.id}) }}"><iconify-icon icon="material-symbols-light:edit" width="25"></iconify-icon></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


        <a href="{{ path('app_borrowing_new') }}" class="btn">Ajouter</a>

{% endblock %}

templates/borrowing/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Borrowing{% endblock %}
 {% block headTitle %}Emprunter du matériel{% endblock %}

{% block body %}
    {# <div class="title">
        <h1>Emprunter du matériel</h1>
    </div> #}
<div class="createMaterial">
    
    {{ include('borrowing/_form.html.twig') }}
</div>

    <a href="{{ path('app_borrowing_index') }}" class="btn">Retour a l'historique</a>
{% endblock %}

templates/borrowing/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Borrowing{% endblock %}
 {% block headTitle %}Détail d'emprunt{% endblock %}

{% block body %}


    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ borrowing.id }}</td>
            </tr>
            <tr>
                <th>Date d'emprunt</th>
                <td>{{ borrowing.borrowDate ? borrowing.borrowDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date de retour estimée</th>
                <td>{{ borrowing.expectedReturnDate ? borrowing.expectedReturnDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date de retour</th>
                <td>
                    {% if borrowing.actualReturnDate is not null %}
                        {{ borrowing.actualReturnDate|date('Y-m-d') }}
                    {% else %}
                        Aucune date de retour définie
                    {% endif %}
                </td>
            </tr>            
            <tr>
                <th>Commentaire</th>
                <td>
                    {% if borrowing.comment is not null %}
                        {{ borrowing.comment }}
                    {% else %}
                       RAS
                    {% endif %}
                </td>
            </tr>
            

            <tr>
                <th>Étudiant</th>
                <td>
                    {% if borrowing.student is not null %}
                        {{ borrowing.student.firstname }}
                    {% else %}
                        Il n'y a personne
                    {% endif %}
                </td>
            </tr>

            <tr>
                <th>Employé</th>
                <td>
                    {% if borrowing.employee is not null %}
                        {{ borrowing.employee.firstname }}
                    {% else %}
                        Il n'y a personne
                    {% endif %}
                </td>
            </tr>


        
            

        </tbody>
    </table>

    <a href="{{ path('app_borrowing_index') }}" class="btn">Retour à l'historique</a>

    <a href="{{ path('app_borrowing_edit', {'id': borrowing.id}) }}" class="btn">Modifier</a>

    {{ include('borrowing/_delete_form.html.twig') }}
{% endblock %}